In [12]:
import numpy as np

In [15]:
m = 3

In [5]:
x = np.array([[1,10], [1,5],[1,4]])
x

array([[ 1, 10],
       [ 1,  5],
       [ 1,  4]])

In [8]:
y = np.array([[7], [4], [3]])
y

array([[7],
       [4],
       [3]])

In [7]:
theta = np.array([[0.5], [0.1]])
theta

array([[0.5],
       [0.1]])

In [24]:
(x @ theta) 

array([[1.5],
       [1. ],
       [0.9]])

In [26]:
(x @ theta)  - y

array([[-5.5],
       [-3. ],
       [-2.1]])

In [30]:
((x @ theta)  - y).sum()

-10.6

In [68]:
dth0 = (1/m) * ((x @ theta)  - y).sum()
dth0

-3.533333333333333

In [70]:
dth1 = (1/m) * x[:,1]@((x @ theta)  - y)
dth1

array([-26.13333333])

In [71]:
dth = 1/m * (x.T@((x @ theta)  - y))
dth

array([[ -3.53333333],
       [-26.13333333]])